package:
  name: hdf5
  version: 1.8.17

source:
  fn: hdf5-1.8.17.tar.bz2
  url: http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2
  md5: 34bd1afa5209259201a41964100d6203

build:
  number: 0
  features:
    - openmpi
  track_features:
    - openmpi

requirements:
  build:
    - zlib
    - openmpi
  run:
    - zlib
    - openmpi

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)
