{% set version = "3.0.1" %}
package:
  name: mpi4py
  version: {{ version }}

source:
  fn: mpi4py-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/m/mpi4py/mpi4py-{{ version }}.tar.gz
  md5: 969bcde3188fb98e0be61b5d78a8745f

build:
    features:
        - openmpi
    track_features:
        - openmpi

requirements:
  build:
    - python
    - setuptools
    - openmpi

  run:
    - python
    - openmpi

test:
  # Python imports
  imports:
    - mpi4py
    - mpi4py.rc
    - mpi4py.dl # [not win]
    - mpi4py.MPI

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/mpi4py/mpi4py/
  license: BSD License
  summary: 'Python bindings for MPI'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
