{% set version = "2.0.1" %}
{% set minor_version = ".".join(version.split(".")[:2]) %}
package:
  name: openmpi
  version: {{ version }}

source:
  fn: openmpi-{{ version }}.tar.bz2
  url: https://www.open-mpi.org/software/ompi/v{{ minor_version }}/downloads/openmpi-{{ version }}.tar.bz2
  md5: 6f78155bd7203039d2448390f3b51c96

about:
  home: http://www.open-mpi.org/
  license: new BSD  (http://www.open-mpi.org/community/license.php)

build:
    features:
        - openmpi
    track_features:
        - openmpi

test:
    commands:
        - ompi_info
          #- mpirun -n 1 echo hi
