{% set version = "3.1.3" %}
{% set minor_version = ".".join(version.split(".")[:2]) %}
package:
  name: openmpi
  version: {{ version }}

source:
  fn: openmpi-{{ version }}.tar.bz2
  url: https://www.open-mpi.org/software/ompi/v{{ minor_version }}/downloads/openmpi-{{ version }}.tar.bz2
  md5: 7456ab54a81b28d6670489a60c9ed23c

about:
  home: http://www.open-mpi.org/
  license: new BSD  (http://www.open-mpi.org/community/license.php)

requirements:
  conflicts:
    - mpich
    - mpich2

build:
  features:
    - openmpi
  track_features:
    - openmpi
  binary_relocation: true
  detect_binary_files_with_prefix: true

test:
  files:
    - test/helloworld.c
    - test/helloworld.cxx
  commands:
    - command -v ompi_info
    - ompi_info
    - command -v mpiexec
    - mpiexec -n 4 hostname
    - command -v mpicc
    - mpicc -show
    - mpicc test/helloworld.c -o helloworld_c
    - mpiexec -n 4 ./helloworld_c
